https://github.com/fastai/fastai/blob/master/courses/dl1/lesson6-rnn.ipynb

In Lesson 4 (http://course.fast.ai/lessons/lesson4.html) we did a word a time. 01:23:30

Now we do a character a time.

A Recurrent Neural Network is no different than what we saw before. The basic issue they solve is to keep state of the long term dependencies, because tokens at the end of a sentence refer to the beginning state often. Note, this can be done with a convolutional network also, but with a RNN it is much more straightforward.

Stateful Representation:

where are we now
long term dependencies
memory
variable length sequences

This is prep for lesson 11: 

TO CHECK: 
Question would be if one can use a character model to kind of build a hidden language that is a translation layer between a source and target language. This might be more visual than useful directly for the algorithm

In [ ]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

from fastai.io import *
from fastai.conv_learner import *

from fastai.column_data import *

## Setup

We're going to download the collected works of Nietzsche to use as our data for this class.

In [ ]:
PATH='data/nietzsche/'

In [ ]:
get_data("https://s3.amazonaws.com/text-datasets/nietzsche.txt", f'{PATH}nietzsche.txt')
text = open(f'{PATH}nietzsche.txt').read()
print('corpus length:', len(text))

corpus length: 600893


In [ ]:
text[:400]

'PREFACE\n\n\nSUPPOSING that Truth is a woman--what then? Is there not ground\nfor suspecting that all philosophers, in so far as they have been\ndogmatists, have failed to understand women--that the terrible\nseriousness and clumsy importunity with which they have usually paid\ntheir addresses to Truth, have been unskilled and unseemly methods for\nwinning a woman? Certainly she has never allowed herself '

In [ ]:
chars = sorted(list(set(text))) ## gives the unique letters
vocab_size = len(chars)+1
print('total chars:', vocab_size)

total chars: 85


Sometimes it's useful to have a zero value in the dataset, e.g. for padding

In [ ]:
chars.insert(0, "\0") ## padding character

''.join(chars[1:-6]) ## this is how our char level vocab 'chars' looks like

'\n !"\'(),-.0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxy'

Map from chars to indices and back again

In [ ]:
char_indices = {c: i for i, c in enumerate(chars)}
indices_char = {i: c for i, c in enumerate(chars)}

idx will be the data we use from now own - it simply converts all the characters to their index (based on the mapping above)

Combining charater with word level can be quite useful e.g. for sequence 2 sequence translations. Instead of treating words as unknown or unusual when newly encountered, one can use a character level model.

'In between' BPE (byte pair encoding): https://arxiv.org/abs/1508.07909

In [ ]:
idx = [char_indices[c] for c in text]

idx[:10]

[40, 42, 29, 30, 25, 27, 29, 1, 1, 1]

In [ ]:
''.join(indices_char[i] for i in idx[:70])

'PREFACE\n\n\nSUPPOSING that Truth is a woman--what then? Is there not gro'

## Three char model

### Create inputs

Create a list of every 4th character, starting at the 0th, 1st, 2nd, then 3rd characters

In [ ]:
## list of all 0,1,2,3, characters
cs=3
c1_dat = [idx[i]   for i in range(0, len(idx)-cs, cs)]
c2_dat = [idx[i+1] for i in range(0, len(idx)-cs, cs)]
c3_dat = [idx[i+2] for i in range(0, len(idx)-cs, cs)]
c4_dat = [idx[i+3] for i in range(0, len(idx)-cs, cs)]

Our inputs

In [ ]:
## input is above 3 lists and we use stack to pluck them together
x1 = np.stack(c1_dat)
x2 = np.stack(c2_dat)
x3 = np.stack(c3_dat)

Our output

In [ ]:
y = np.stack(c4_dat)

The first 4 inputs and outputs

In [ ]:
## we use 3 characters to predict the 4th
x1[:4], x2[:4], x3[:4]

(array([40, 30, 29,  1]), array([42, 25,  1, 43]), array([29, 27,  1, 45]))

In [ ]:
## so we use e.g. 40, 42, 29 to predict 29. 29 is the next char below then. 
## then we use 29,25,27 to predict 1 and so on
y[:4]

array([30, 29,  1, 40])

In [ ]:
x1.shape, y.shape

((200295,), (200295,))

### Create and train model

Pick a size for our hidden state

In [ ]:
## how many activations do need
n_hidden = 256

The number of latent factors to create (i.e. the size of the embedding matrix)

In [ ]:
## size of our embeddings / around half the number of characters
n_fac = 42

In [3]:
## This Char Model is a standard fully connected Model ! 
## The one addition is that we add each of the inouts one at a time


## Note all coloured arrows use each one matrix, why?
## GREEN: For the characters e.g. why would a character semantically have a different meaning if 1st, 2nd or 3rd?
## ORANGE: for moving between characters, weights should be similar too.

## Both arrows saY : take a character and represent it as a set of features

class Char3Model(nn.Module):
    def __init__(self, vocab_size, n_fac):
        super().__init__()
        ## IN: vocabulary size / Out: factors in the embedding
        self.e = nn.Embedding(vocab_size, n_fac)

        # The 'green arrow' from our diagram - the layer operation from input to hidden
        self.l_in = nn.Linear(n_fac, n_hidden)

        # The 'orange arrow' from our diagram - the layer operation from hidden to hidden
        self.l_hidden = nn.Linear(n_hidden, n_hidden)
        
        # The 'blue arrow' from our diagram - the layer operation from hidden to output
        self.l_out = nn.Linear(n_hidden, vocab_size)
    ## we pass in 3 characters
   
## NOTE this code here is rather repetitive: we have 2x3 lines that almost identical. 
## The last one should be a loop
    def forward(self, c1, c2, c3):
        ## pass every character through an embedding / linear layer and relu
        
        ## dimensions:
            ## self.e: length 42 --> l_in make it of size n_hidden -->
        in1 = F.relu(self.l_in(self.e(c1)))
        in2 = F.relu(self.l_in(self.e(c2)))
        in3 = F.relu(self.l_in(self.e(c3)))
        
        ## Here we always take the previous layer and h and add one of the results from the char
        h = V(torch.zeros(in1.size()).cuda()) ## hs is just a bunch of zeros
        ## dimensions:
            ## self.l_hidden --> also returns sth of size n_hidden
            ## in2 was n_hidden h is n_hidden --> join them together to 2 n_hidden
            ## self.l_hidden --> returns size n_hidden
        
        
## hyperbolic tanh: 
    ## - like a sigmoid offset
    ## common to use in this transition because it stops it from 'flying' too high or too low
        
        h = F.tanh(self.l_hidden(h+in1))
        h = F.tanh(self.l_hidden(h+in2))
        h = F.tanh(self.l_hidden(h+in3))
        
        return F.log_softmax(self.l_out(h))

NameError: name 'nn' is not defined

In [ ]:
## Columnard Model Data: whatever you put in where here x1,x2,x3 
## it goes to above forward def forward(self, c1, c2, c3)

md = ColumnarModelData.from_arrays('.', [-1], np.stack([x1,x2,x3], axis=1), y, bs=512)

In [ ]:
## create a standard pytorch model
m = Char3Model(vocab_size, n_fac).cuda()

In [ ]:
## this allows peeking inside to see what's going on
it = iter(md.trn_dl) ## iteratr through the training set
*xs,yt = next(it) ## call next to grab a mini batch that returns all xs, yt tensors
t = m(*V(xs)) ## use a model as it was a function. pass variablised version of tensors 
## len xs = 3 from forward(self, c1, c2, c3):
## xs[0].size --> 512 i.e. the batch size
## not one hot encoded, we use an embedding

In [ ]:
## pytorch optimiser
opt = optim.Adam(m.parameters(), 1e-2)

In [ ]:
## fit the model
fit(m, md, 1, opt, F.nll_loss)

A Jupyter Widget

[ 0.       2.09627  6.52849]                                 



In [ ]:
set_lrs(opt, 0.001)

In [ ]:
fit(m, md, 1, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.84525  6.52312]                                 



### Test model

In [ ]:
## pass in 3 chars, e.g. 'y. '

def get_next(inp):
    ## turn input into a tensor of an array of the character index for each character in that list
    idxs = T(np.array([char_indices[c] for c in inp]))
    p = m(*VV(idxs)) ## turn those into variable, then pass that to our model
    i = np.argmax(to_np(p)) ## argmax to get the right character. to_np to convert into numpy format
    return chars[i]

In [ ]:
get_next('y. ')

'T'

In [ ]:
get_next('ppl')

'e'

In [ ]:
get_next(' th')

'e'

In [ ]:
get_next('and')

' '

## Our first RNN!

This is the same as Char3Model. 
Only instead of 2 x the same step we make a loop. Also, the very 1st inout char can be part of the loop and we can start out with zero initialisation. 

Note, we have shared weights in RNN. In convolutional networks we share filters.

### Create inputs

This is the size of our unrolled RNN.

In [ ]:
cs=8

For each of 0 through 7, create a list of every 8th character with that starting point. These will be the 8 inputs to our model.

In [ ]:
c_in_dat = [[idx[i+j] for i in range(cs)] for j in range(len(idx)-cs)]

Then create a list of the next character in each of these series. This will be the labels for our model.

In [ ]:
c_out_dat = [idx[j+cs] for j in range(len(idx)-cs)]

In [ ]:
xs = np.stack(c_in_dat, axis=0)

In [ ]:
xs.shape

(600884, 8)

In [ ]:
y = np.stack(c_out_dat)

So each column below is one series of 8 characters from the text.

In [ ]:
xs[:cs,:cs]

array([[40, 42, 29, 30, 25, 27, 29,  1],
       [42, 29, 30, 25, 27, 29,  1,  1],
       [29, 30, 25, 27, 29,  1,  1,  1],
       [30, 25, 27, 29,  1,  1,  1, 43],
       [25, 27, 29,  1,  1,  1, 43, 45],
       [27, 29,  1,  1,  1, 43, 45, 40],
       [29,  1,  1,  1, 43, 45, 40, 40],
       [ 1,  1,  1, 43, 45, 40, 40, 39]])

How to read this: 
- 0-8: 40, 42, 29, 30, 25, 27, 29,  1 --> next one from next line last one  so 1
- 1-9: 42, 29, 30, 25, 27, 29,  1,  1 --> next one from next line last one  so 1
- 2-10: 29, 30, 25, 27, 29,  1,  1,  1 --> next one from next line last one  so 43
- 3-11: 30, 25, 27, 29,  1,  1,  1, 43 --> next one from next line last one  ...


Note, we re-calculate the same thing all over again with overlappings. 


...and this is the next character after each sequence.

In [ ]:
y[:cs] ## this is last column above, so always the prediction

array([ 1,  1, 43, 45, 40, 40, 39, 43])

### Create and train model

In [ ]:
val_idx = get_cv_idxs(len(idx)-cs-1)

In [ ]:
md = ColumnarModelData.from_arrays('.', val_idx, xs, y, bs=512)

In [ ]:
## Note this can be a deep network, eg. 8 layers.
## Therefore, careful with training (deeper is harder to train)
class CharLoopModel(nn.Module):
    # This is an RNN!
    def __init__(self, vocab_size, n_fac):
        super().__init__()
        self.e = nn.Embedding(vocab_size, n_fac)
        self.l_in = nn.Linear(n_fac, n_hidden)
        self.l_hidden = nn.Linear(n_hidden, n_hidden)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        
    def forward(self, *cs):
        bs = cs[0].size(0)
        h = V(torch.zeros(bs, n_hidden).cuda())
## Same as before in Char3Model        
## Only, this loop is new generalising Char3Model      
        for c in cs:
            inp = F.relu(self.l_in(self.e(c)))
## NOTE: adding h and inp hidden and input state h: encoding of characters so far input: encoding of characters
        ## adding them might make loose information, see below
            h = F.tanh(self.l_hidden(h+inp))
#######################
## BEFORE, now looped

        ##in1 = F.relu(self.l_in(self.e(c1)))
        ##in2 = F.relu(self.l_in(self.e(c2)))
        ##in3 = F.relu(self.l_in(self.e(c3)))
        
        
        ##h = V(torch.zeros(in1.size()).cuda()) ## hs is just a bunch of zeros
        
        ##h = F.tanh(self.l_hidden(h+in1))
        ##h = F.tanh(self.l_hidden(h+in2))
        ##h = F.tanh(self.l_hidden(h+in3))

#########################
        
        return F.log_softmax(self.l_out(h), dim=-1)

In [ ]:
m = CharLoopModel(vocab_size, n_fac).cuda()
opt = optim.Adam(m.parameters(), 1e-2)

In [ ]:
fit(m, md, 1, opt, F.nll_loss)

A Jupyter Widget

[ 0.       2.02986  1.99268]                                



In [ ]:
set_lrs(opt, 0.001)

In [ ]:
fit(m, md, 1, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.73588  1.75103]                                 



In [ ]:
##Heuristic: to combine things of differen kind, concatenate do not add to not loose information

class CharLoopConcatModel(nn.Module):
    def __init__(self, vocab_size, n_fac):
        super().__init__()
        self.e = nn.Embedding(vocab_size, n_fac)
## we need to add n_fac + n_hidden --> BEFORE / ABOVE: self.l_in = nn.Linear(n_fac, n_hidden)
## this way the dimensions check out
        self.l_in = nn.Linear(n_fac+n_hidden, n_hidden)
        self.l_hidden = nn.Linear(n_hidden, n_hidden)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        
    def forward(self, *cs):
        bs = cs[0].size(0)
        ## for loop needs a starting point to be able to work
        h = V(torch.zeros(bs, n_hidden).cuda())
        for c in cs:
            ## size: n_fac + n_hidden
            inp = torch.cat((h, self.e(c)), 1)
            ## back to size n_hidden
            inp = F.relu(self.l_in(inp))
            ## same square matrix as before 
            h = F.tanh(self.l_hidden(inp))
        
        return F.log_softmax(self.l_out(h), dim=-1)

In [ ]:
m = CharLoopConcatModel(vocab_size, n_fac).cuda()
opt = optim.Adam(m.parameters(), 1e-3)

In [ ]:
it = iter(md.trn_dl)
*xs,yt = next(it)
t = m(*V(xs))

In [ ]:
fit(m, md, 1, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.81654  1.78501]                                



In [ ]:
set_lrs(opt, 1e-4)

In [ ]:
fit(m, md, 1, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.69008  1.69936]                                 



### Test model

In [ ]:
def get_next(inp):
    idxs = T(np.array([char_indices[c] for c in inp]))
    p = m(*VV(idxs))
    i = np.argmax(to_np(p))
    return chars[i]

In [ ]:
get_next('for thos') ## we pass in 8 things

'e'

In [ ]:
get_next('part of ')

't'

In [ ]:
get_next('queens a')

'n'

## RNN with pytorch

What can pytorch do?
- write loop
- write input layers

CharRnn is like CharLoopConcatModel, only written in pytorch

In [ ]:
class CharRnn(nn.Module):
    def __init__(self, vocab_size, n_fac):
        super().__init__()
        self.e = nn.Embedding(vocab_size, n_fac)
        ## create an RNN
        self.rnn = nn.RNN(n_fac, n_hidden) ## wrapped up and made easier than in CharLoopConcatModel
        self.l_out = nn.Linear(n_hidden, vocab_size)
        
    def forward(self, *cs):
        bs = cs[0].size(0)
        ## starting point for the for loop
        ## the 1 here is about the backward RNN, 1 indicates additional axis on tensor to keep track
        h = V(torch.zeros(1, bs, n_hidden)) ## rank 3 tensor / above its a rank 2 tensor
        inp = self.e(torch.stack(cs))
        ## for loop in here
        ## h is the initial hidden state and the starting point
        ## hidden state has size 256 represents the shift from one char to another one
        outp,h = self.rnn(inp, h) ## getting back the hidden state is useful. 
        
        ## pytorch appends h to a tensor, here we just want the last oen: -1
        ## pass through outp to get correct vocab size
        return F.log_softmax(self.l_out(outp[-1]), dim=-1)

In [ ]:
m = CharRnn(vocab_size, n_fac).cuda()
opt = optim.Adam(m.parameters(), 1e-3)

In [ ]:
it = iter(md.trn_dl)
*xs,yt = next(it)

In [ ]:
t = m.e(V(torch.stack(xs)))
t.size()

torch.Size([8, 512, 42])

In [ ]:
ht = V(torch.zeros(1, 512,n_hidden))
outp, hn = m.rnn(t, ht)
outp.size(), hn.size()

(torch.Size([8, 512, 256]), torch.Size([1, 512, 256]))

In [ ]:
t = m(*V(xs)); t.size()

torch.Size([512, 85])

In [ ]:
fit(m, md, 4, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.86065  1.84255]                                 
[ 1.       1.68014  1.67387]                                 
[ 2.       1.58828  1.59169]                                 
[ 3.       1.52989  1.54942]                                 



In [ ]:
set_lrs(opt, 1e-4)

In [ ]:
fit(m, md, 2, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.46841  1.50966]                                 
[ 1.       1.46482  1.5039 ]                                 



### Test model

In [ ]:
def get_next(inp):
    idxs = T(np.array([char_indices[c] for c in inp]))
    p = m(*VV(idxs))
    i = np.argmax(to_np(p))
    return chars[i]

In [ ]:
get_next('for thos')

'e'

In [ ]:
def get_next_n(inp, n):
    res = inp
    for i in range(n):
        c = get_next(inp)
        res += c
        inp = inp[1:]+c ## result from last run, so we feed into each other
    return res

In [ ]:
get_next_n('for thos', 40) ## give start sequence

'for those the same the same the same the same th'

## Multi-output model

Idea: we always put the outpit layer in the loop, i.e. there is no one output (next char) but rather for every input we give an output, i.e. for 3 inouts we have 3 outputs.

Technically, 'small step' but helps a lot with efficieny and performance. Above, we re-calculated a lot.

### Setup

Let's take non-overlapping sets of characters this time

In [ ]:
c_in_dat = [[idx[i+j] for i in range(cs)] for j in range(0, len(idx)-cs-1, cs)]

Then create the exact same thing, offset by 1, as our labels

In [ ]:
c_out_dat = [[idx[i+j] for i in range(cs)] for j in range(1, len(idx)-cs, cs)]

In [ ]:
xs = np.stack(c_in_dat)
xs.shape

(75111, 8)

In [ ]:
ys = np.stack(c_out_dat)
ys.shape

(75111, 8)

Non overlapping, after we see chars 0-7 we predict 1-8. This is the same as above, but much more efficient

In [ ]:
xs[:cs,:cs]

array([[40, 42, 29, 30, 25, 27, 29,  1],
       [ 1,  1, 43, 45, 40, 40, 39, 43],
       [33, 38, 31,  2, 73, 61, 54, 73],
       [ 2, 44, 71, 74, 73, 61,  2, 62],
       [72,  2, 54,  2, 76, 68, 66, 54],
       [67,  9,  9, 76, 61, 54, 73,  2],
       [73, 61, 58, 67, 24,  2, 33, 72],
       [ 2, 73, 61, 58, 71, 58,  2, 67]])

In [ ]:
ys[:cs,:cs]

array([[42, 29, 30, 25, 27, 29,  1,  1],
       [ 1, 43, 45, 40, 40, 39, 43, 33],
       [38, 31,  2, 73, 61, 54, 73,  2],
       [44, 71, 74, 73, 61,  2, 62, 72],
       [ 2, 54,  2, 76, 68, 66, 54, 67],
       [ 9,  9, 76, 61, 54, 73,  2, 73],
       [61, 58, 67, 24,  2, 33, 72,  2],
       [73, 61, 58, 71, 58,  2, 67, 68]])

### Create and train model

In [ ]:
val_idx = get_cv_idxs(len(xs)-cs-1)

In [ ]:
md = ColumnarModelData.from_arrays('.', val_idx, xs, ys, bs=512)

In [ ]:
## same as above, only 1 change below
## optimisation ( next lesson): we should keep the hidden state between batches as sth was learnt
class CharSeqRnn(nn.Module):
    def __init__(self, vocab_size, n_fac):
        super().__init__()
        self.e = nn.Embedding(vocab_size, n_fac)
        self.rnn = nn.RNN(n_fac, n_hidden)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        
    def forward(self, *cs):
        bs = cs[0].size(0)
        h = V(torch.zeros(1, bs, n_hidden))
        ## Optimisation: avoid gradient explosion with identity matrix
        inp = self.e(torch.stack(cs))
        outp,h = self.rnn(inp, h)
## note above we had -1 for last layer. Now we grab all
        return F.log_softmax(self.l_out(outp), dim=-1) 

In [ ]:
m = CharSeqRnn(vocab_size, n_fac).cuda()
opt = optim.Adam(m.parameters(), 1e-3)

In [ ]:
it = iter(md.trn_dl)
*xst,yt = next(it)
## yt labels is 512 x 8

- Negative loss likelihood function expects to receive 2 rank 1(2) tensors
- In a RNN we have 8 timesteps with 84 for each and that for 512 items in mini batch -- rank 3 tensor
- Pytorch would crash 

In [ ]:
# custom loss function 
def nll_loss_seq(inp, targ):
    ## transpose
    ## pytorch: 1 timesteps, 2 batch size, 3 hidden state
    sl,bs,nh = inp.size() ## 8, 512, 256
    ## yt.size 512  x 8 
    ## transpose the 1st 2 axis. 
    ## pytorch keeps internal metadata saying, sth like this should be transposed
    ## sometimes contiguous error --> just add contiguors
    ## view(-1) is numpy rehsape to flatten out
    targ = targ.transpose(0,1).contiguous().view(-1)
    ## predictions have length 84
    return F.nll_loss(inp.view(-1,nh), targ) ## call the pytorch version expecting 2

In [ ]:
## lowest level fast.ai abstraction 
fit(m, md, 4, opt, nll_loss_seq) ## other than MD (test, training & validation set) this is all pytorch standard stuff

A Jupyter Widget

[ 0.       2.59241  2.40251]                                
[ 1.       2.28474  2.19859]                                
[ 2.       2.13883  2.08836]                                
[ 3.       2.04892  2.01564]                                



In [ ]:
set_lrs(opt, 1e-4)

In [ ]:
fit(m, md, 1, opt, nll_loss_seq)

A Jupyter Widget

[ 0.       1.99819  2.00106]                               



### Identity init!

This avoids gradient explosion, init with identity matrix: one multiplies matrixes 
and with identity matrix it neither shrinks or explodes

Geoffrey Hinton https://arxiv.org/abs/1504.00941

In [ ]:
m = CharSeqRnn(vocab_size, n_fac).cuda()
opt = optim.Adam(m.parameters(), 1e-2)

In [ ]:
## this is the implementation of the paper
m.rnn.weight_hh_l0.data.copy_(torch.eye(n_hidden)) ## eye is the identity matrix in pytorch


    1     0     0  ...      0     0     0
    0     1     0  ...      0     0     0
    0     0     1  ...      0     0     0
       ...          ⋱          ...       
    0     0     0  ...      1     0     0
    0     0     0  ...      0     1     0
    0     0     0  ...      0     0     1
[torch.cuda.FloatTensor of size 256x256 (GPU 0)]

In [ ]:
fit(m, md, 4, opt, nll_loss_seq)

A Jupyter Widget

[ 0.       2.39428  2.21111]                                
[ 1.       2.10381  2.03275]                                
[ 2.       1.99451  1.96393]                               
[ 3.       1.93492  1.91763]                                



In [ ]:
set_lrs(opt, 1e-3)

In [ ]:
fit(m, md, 4, opt, nll_loss_seq)

A Jupyter Widget

[ 0.       1.84035  1.85742]                                
[ 1.       1.82896  1.84887]                                
[ 2.       1.81879  1.84281]                               
[ 3.       1.81337  1.83801]                                



## Stateful model

### Setup

In [ ]:
from torchtext import vocab, data

from fastai.nlp import *
from fastai.lm_rnn import *

PATH='data/nietzsche/'

TRN_PATH = 'trn/'
VAL_PATH = 'val/'
TRN = f'{PATH}{TRN_PATH}'
VAL = f'{PATH}{VAL_PATH}'

# Note: The student needs to practice her shell skills and prepare her own dataset before proceeding:
# - trn/trn.txt (first 80% of nietzsche.txt)
# - val/val.txt (last 20% of nietzsche.txt)

%ls {PATH}

models/  nietzsche.txt  trn/  val/


In [ ]:
%ls {PATH}trn

trn.txt


In [ ]:
TEXT = data.Field(lower=True, tokenize=list)
bs=64; bptt=8; n_fac=42; n_hidden=256

FILES = dict(train=TRN_PATH, validation=VAL_PATH, test=VAL_PATH)
md = LanguageModelData.from_text_files(PATH, TEXT, **FILES, bs=bs, bptt=bptt, min_freq=3)

len(md.trn_dl), md.nt, len(md.trn_ds), len(md.trn_ds[0].text)

(963, 56, 1, 493747)

### RNN

In [ ]:
class CharSeqStatefulRnn(nn.Module):
    def __init__(self, vocab_size, n_fac, bs):
        self.vocab_size = vocab_size
        super().__init__()
        self.e = nn.Embedding(vocab_size, n_fac)
        self.rnn = nn.RNN(n_fac, n_hidden)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        self.init_hidden(bs)
        
    def forward(self, cs):
        bs = cs[0].size(0)
        if self.h.size(1) != bs: self.init_hidden(bs)
        outp,h = self.rnn(self.e(cs), self.h)
        self.h = repackage_var(h)
        return F.log_softmax(self.l_out(outp), dim=-1).view(-1, self.vocab_size)
    
    def init_hidden(self, bs): self.h = V(torch.zeros(1, bs, n_hidden))

In [ ]:
m = CharSeqStatefulRnn(md.nt, n_fac, 512).cuda()
opt = optim.Adam(m.parameters(), 1e-3)

In [ ]:
fit(m, md, 4, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.81983  1.81247]                                 
[ 1.       1.63097  1.66228]                                 
[ 2.       1.54433  1.57824]                                 
[ 3.       1.48563  1.54505]                                 



In [ ]:
set_lrs(opt, 1e-4)

fit(m, md, 4, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.4187   1.50374]                                 
[ 1.       1.41492  1.49391]                                 
[ 2.       1.41001  1.49339]                                 
[ 3.       1.40756  1.486  ]                                 



### RNN loop

In [ ]:
# From the pytorch source

def RNNCell(input, hidden, w_ih, w_hh, b_ih, b_hh):
    return F.tanh(F.linear(input, w_ih, b_ih) + F.linear(hidden, w_hh, b_hh))

In [ ]:
class CharSeqStatefulRnn2(nn.Module):
    def __init__(self, vocab_size, n_fac, bs):
        super().__init__()
        self.vocab_size = vocab_size
        self.e = nn.Embedding(vocab_size, n_fac)
        self.rnn = nn.RNNCell(n_fac, n_hidden)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        self.init_hidden(bs)
        
    def forward(self, cs):
        bs = cs[0].size(0)
        if self.h.size(1) != bs: self.init_hidden(bs)
        outp = []
        o = self.h
        for c in cs: 
            o = self.rnn(self.e(c), o)
            outp.append(o)
        outp = self.l_out(torch.stack(outp))
        self.h = repackage_var(o)
        return F.log_softmax(outp, dim=-1).view(-1, self.vocab_size)
    
    def init_hidden(self, bs): self.h = V(torch.zeros(1, bs, n_hidden))

In [ ]:
m = CharSeqStatefulRnn2(md.nt, n_fac, 512).cuda()
opt = optim.Adam(m.parameters(), 1e-3)

In [ ]:
fit(m, md, 4, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.81013  1.7969 ]                                 
[ 1.       1.62515  1.65346]                                 
[ 2.       1.53913  1.58065]                                 
[ 3.       1.48698  1.54217]                                 



### GRU

In [ ]:
class CharSeqStatefulGRU(nn.Module):
    def __init__(self, vocab_size, n_fac, bs):
        super().__init__()
        self.vocab_size = vocab_size
        self.e = nn.Embedding(vocab_size, n_fac)
        self.rnn = nn.GRU(n_fac, n_hidden)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        self.init_hidden(bs)
        
    def forward(self, cs):
        bs = cs[0].size(0)
        if self.h.size(1) != bs: self.init_hidden(bs)
        outp,h = self.rnn(self.e(cs), self.h)
        self.h = repackage_var(h)
        return F.log_softmax(self.l_out(outp), dim=-1).view(-1, self.vocab_size)
    
    def init_hidden(self, bs): self.h = V(torch.zeros(1, bs, n_hidden))

In [ ]:
# From the pytorch source code - for reference

def GRUCell(input, hidden, w_ih, w_hh, b_ih, b_hh):
    gi = F.linear(input, w_ih, b_ih)
    gh = F.linear(hidden, w_hh, b_hh)
    i_r, i_i, i_n = gi.chunk(3, 1)
    h_r, h_i, h_n = gh.chunk(3, 1)

    resetgate = F.sigmoid(i_r + h_r)
    inputgate = F.sigmoid(i_i + h_i)
    newgate = F.tanh(i_n + resetgate * h_n)
    return newgate + inputgate * (hidden - newgate)

In [ ]:
m = CharSeqStatefulGRU(md.nt, n_fac, 512).cuda()

opt = optim.Adam(m.parameters(), 1e-3)

In [ ]:
fit(m, md, 6, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.68409  1.67784]                                 
[ 1.       1.49813  1.52661]                                 
[ 2.       1.41674  1.46769]                                 
[ 3.       1.36359  1.43818]                                 
[ 4.       1.33223  1.41777]                                 
[ 5.       1.30217  1.40511]                                 



In [ ]:
set_lrs(opt, 1e-4)

In [ ]:
fit(m, md, 3, opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.22708  1.36926]                                 
[ 1.       1.21948  1.3696 ]                                 
[ 2.       1.22541  1.36969]                                 



### Putting it all together: LSTM

In [ ]:
from fastai import sgdr

n_hidden=512

In [ ]:
class CharSeqStatefulLSTM(nn.Module):
    def __init__(self, vocab_size, n_fac, bs, nl):
        super().__init__()
        self.vocab_size,self.nl = vocab_size,nl
        self.e = nn.Embedding(vocab_size, n_fac)
        self.rnn = nn.LSTM(n_fac, n_hidden, nl, dropout=0.5)
        self.l_out = nn.Linear(n_hidden, vocab_size)
        self.init_hidden(bs)
        
    def forward(self, cs):
        bs = cs[0].size(0)
        if self.h[0].size(1) != bs: self.init_hidden(bs)
        outp,h = self.rnn(self.e(cs), self.h)
        self.h = repackage_var(h)
        return F.log_softmax(self.l_out(outp), dim=-1).view(-1, self.vocab_size)
    
    def init_hidden(self, bs):
        self.h = (V(torch.zeros(self.nl, bs, n_hidden)),
                  V(torch.zeros(self.nl, bs, n_hidden)))

In [ ]:
m = CharSeqStatefulLSTM(md.nt, n_fac, 512, 2).cuda()
lo = LayerOptimizer(optim.Adam, m, 1e-2, 1e-5)

In [ ]:
os.makedirs(f'{PATH}models', exist_ok=True)

In [ ]:
fit(m, md, 2, lo.opt, F.nll_loss)

A Jupyter Widget

[ 0.       1.72032  1.64016]                                 
[ 1.       1.62891  1.58176]                                 



In [ ]:
on_end = lambda sched, cycle: save_model(m, f'{PATH}models/cyc_{cycle}')
cb = [CosAnneal(lo, len(md.trn_dl), cycle_mult=2, on_cycle_end=on_end)]
fit(m, md, 2**4-1, lo.opt, F.nll_loss, callbacks=cb)

A Jupyter Widget

[ 0.       1.47969  1.4472 ]                                 
[ 1.       1.51411  1.46612]                                 
[ 2.       1.412    1.39909]                                 
[ 3.       1.53689  1.48337]                                 
[ 4.       1.47375  1.43169]                                 
[ 5.       1.39828  1.37963]                                 
[ 6.       1.34546  1.35795]                                 
[ 7.       1.51999  1.47165]                                 
[ 8.       1.48992  1.46146]                                 
[ 9.       1.45492  1.42829]                                 
[ 10.        1.42027   1.39028]                              
[ 11.        1.3814    1.36539]                              
[ 12.        1.33895   1.34178]                              
[ 13.        1.30737   1.32871]                              
[ 14.        1.28244   1.31518]                              



In [ ]:
on_end = lambda sched, cycle: save_model(m, f'{PATH}models/cyc_{cycle}')
cb = [CosAnneal(lo, len(md.trn_dl), cycle_mult=2, on_cycle_end=on_end)]
fit(m, md, 2**6-1, lo.opt, F.nll_loss, callbacks=cb)

A Jupyter Widget

[ 0.       1.46053  1.43462]                                 
[ 1.       1.51537  1.47747]                                 
[ 2.       1.39208  1.38293]                                 
[ 3.       1.53056  1.49371]                                 
[ 4.       1.46812  1.43389]                                 
[ 5.       1.37624  1.37523]                                 
[ 6.       1.3173   1.34022]                                 
[ 7.       1.51783  1.47554]                                 
[ 8.       1.4921   1.45785]                                 
[ 9.       1.44843  1.42215]                                 
[ 10.        1.40948   1.40858]                              
[ 11.        1.37098   1.36648]                              
[ 12.        1.32255   1.33842]                              
[ 13.        1.28243   1.31106]                              
[ 14.        1.25031   1.2918 ]                              
[ 15.        1.49236   1.45316]                              
[ 16.   

### Test

In [ ]:
def get_next(inp):
    idxs = TEXT.numericalize(inp)
    p = m(VV(idxs.transpose(0,1)))
    r = torch.multinomial(p[-1].exp(), 1)
    return TEXT.vocab.itos[to_np(r)[0]]

In [ ]:
get_next('for thos')

'e'

In [ ]:
def get_next_n(inp, n):
    res = inp
    for i in range(n):
        c = get_next(inp)
        res += c
        inp = inp[1:]+c
    return res

In [ ]:
print(get_next_n('for thos', 400))

for those the skemps), or
imaginates, though they deceives. it should so each ourselvess and new
present, step absolutely for the
science." the contradity and
measuring, 
the whole!

293. perhaps, that every life a values of blood
of
intercourse when it senses there is unscrupulus, his very rights, and still impulse, love?
just after that thereby how made with the way anything, and set for harmless philos
